
name: Auto tag and npm publish based on commit msg
on: 
  push:
    branches:
    - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'

      - name: 'Show current version'
        run: grep  '"version"' package.json

      - name:  'Automated Version Bump'
        id: version-bump
        uses:  'phips28/gh-action-bump-version@master'
        with:
          minor-wording:  '[RELEASE]'
          skip-push:  'true'
          tag-prefix:  'v'

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
          OLD_TAG: ${{ steps.version-bump.outputs.current }}
        run: echo ${OLD_TAG} ${NEW_TAG}

      # Setup .npmrc file to publish to npm
      - name: Setup Node.js environment
        if: $NEW_TAG != $OLD_TAG
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@openbeta'

      - name: NPM publish
        if: $NEW_TAG != $OLD_TAG
        run: yarn install --no-progress && yarn lint && yarn test && yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

